version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    restart: "always"

  api:
    build: ./api
    ports:
      - "3000:3000"
    restart: "always"
    env_file:
      - ./api/.env
