version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: production
    image: lul-app:latest
    ports:
      - "8080:8080"
    restart: "always"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    image: lul-api:latest
    ports:
      - "3000:3000"
    restart: "always"
    env_file:
      - ./api/.env

  email:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: email
    image: lul-email:latest
    command: ["/bin/true"]

  cert-check:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: cert-check
    image: lul-cert-check:latest
    command: ["/bin/true"]
